Entities, repositories, dtomappers
Mikhail-Lukichev/classified-ads-website-backend pull request #2
Opened 2024-04-11 18:57 UTC by Mikhail-Lukichev

2024-04-12 10:25 UTC, OlgaLugacheva requested changes

2024-04-12 10:25 UTC, OlgaLugacheva commented on src/main/java/ru/skypro/homework/controller/AdsController.java
> +                System.out.println(e.fillInStackTrace());
стек трейс точно не нужно выводить, если что-то пошло не так с сохраненияем , нужно сообщить об этом пользователю, либо это исключение отлавливать и собирать ответ, либо перехватывать другим исключением

2024-04-12 10:25 UTC, OlgaLugacheva commented on src/main/java/ru/skypro/homework/controller/AdsController.java
> +        if (authentication.isAuthenticated()) {
в принципе такая проверка не нужно,  в дальнейшем вы будете настраивать фильтры, и запрос сюда просто без аутентификации не провалится

2024-04-12 10:25 UTC, OlgaLugacheva commented on src/main/java/ru/skypro/homework/controller/AdsController.java
> +                Ad foundAd = adService.getById(id).get();
очень много проверок на isPresent, Optional в принципе предоставляет более красивый синтаксический схар для обработки таких ситуаций

2024-04-12 10:25 UTC, OlgaLugacheva commented on src/main/java/ru/skypro/homework/controller/AdsController.java
> +                updateAd.setAdImage(foundAd.getAdImage());
лучше вот такой громадный маппинг убирать в сервис

2024-04-12 10:25 UTC, OlgaLugacheva commented on src/main/java/ru/skypro/homework/controller/AdsController.java
> +            Author author = authorService.getByEmail(email).get();
небезопасный get()

2024-04-12 10:25 UTC, OlgaLugacheva commented on src/main/java/ru/skypro/homework/controller/AdsController.java
> +                    System.out.println(e.fillInStackTrace());
см выше похожий комментарий

2024-04-12 10:25 UTC, OlgaLugacheva commented on src/main/java/ru/skypro/homework/controller/ImageController.java
> +                throw new RuntimeException(e);
свое исключение и подумать как обработать с нужным ответом

2024-04-12 10:25 UTC, OlgaLugacheva commented on src/main/java/ru/skypro/homework/controller/UserController.java
> +            Author author = authorService.getByEmail(authentication.getName()).orElseThrow();
какое исключение бросаем ? лучше специфицировать

2024-04-12 10:25 UTC, OlgaLugacheva commented on src/main/java/ru/skypro/homework/mapper/AuthorMapper.java
> +        userDto.setImage("/image/avatar/" + author.getId());
ничего плохого тут нет, но можно вынести путь константу или в конфиг, а так ничего страшного

2024-04-13 18:37 UTC, Mikhail-Lukichev commented on src/main/java/ru/skypro/homework/controller/AdsController.java
> +                System.out.println(e.fillInStackTrace());
Пока не очень понял. В этом эндпоинте я могу вернуть пользователю статусы 201 created или 401 unauthorized. 
Пока переделал на возврат статуса 500 internal server error.

2024-04-13 18:39 UTC, Mikhail-Lukichev commented on src/main/java/ru/skypro/homework/controller/AdsController.java
> +        if (authentication.isAuthenticated()) {
А как тогда возвращать статус 401 unauthorized? Этот статус будет возвращен при помощи фильтров?

2024-04-13 18:43 UTC, Mikhail-Lukichev commented on src/main/java/ru/skypro/homework/controller/AdsController.java
> +                Ad foundAd = adService.getById(id).get();
А что лучше использовать в таком случае?
Я это проверку делаю для возврата статуса 404 not found.

2024-04-13 18:54 UTC, Mikhail-Lukichev commented on src/main/java/ru/skypro/homework/controller/AdsController.java
> +                updateAd.setAdImage(foundAd.getAdImage());
Сделано, спасибо

2024-04-13 18:55 UTC, Mikhail-Lukichev commented on src/main/java/ru/skypro/homework/controller/AdsController.java
> +            Author author = authorService.getByEmail(email).get();
Имеется в виду authentication.getName()? А как лучше сделать?

2024-04-13 18:56 UTC, Mikhail-Lukichev commented on src/main/java/ru/skypro/homework/controller/AdsController.java
> +                    System.out.println(e.fillInStackTrace());
принято

2024-04-13 19:10 UTC, Mikhail-Lukichev commented on src/main/java/ru/skypro/homework/controller/ImageController.java
> +                throw new RuntimeException(e);
Создал свое ислючение возвращающее статус 500 Internal Server Error

2024-04-13 19:13 UTC, Mikhail-Lukichev commented on src/main/java/ru/skypro/homework/controller/UserController.java
> +            Author author = authorService.getByEmail(authentication.getName()).orElseThrow();
Создал свое исключение возвращающее  статус 404 Not Found

2024-04-13 19:21 UTC, Mikhail-Lukichev commented on src/main/java/ru/skypro/homework/mapper/AuthorMapper.java
> +        userDto.setImage("/image/avatar/" + author.getId());
вынес в конфиг. Контроллер не менял

2024-04-14 10:21 UTC, OlgaLugacheva commented on src/main/java/ru/skypro/homework/controller/AdsController.java
> +        if (authentication.isAuthenticated()) {
Да, все верно, если пользователь не аутентифицирован, то в эту логику вообще  выполнение не зайдет, поэтому это бесполезная проверка, единственное, что можно проверять, что , например, при редактировании объявления редактируется объявление именно этого конкретного пользователя

2024-04-14 10:22 UTC, OlgaLugacheva commented on src/main/java/ru/skypro/homework/controller/AdsController.java
> +                Ad foundAd = adService.getById(id).get();
orElseThrow например и бросать исключение со респонс - статусом NotFound

2024-04-14 10:23 UTC, OlgaLugacheva commented on src/main/java/ru/skypro/homework/controller/AdsController.java
> +            Author author = authorService.getByEmail(email).get();
нет именно небезопасный get() , лучше orElseThrow опять же, например

2024-04-14 10:24 UTC, OlgaLugacheva commented on src/main/java/ru/skypro/homework/controller/UserController.java
> +            Author author = authorService.getByEmail(authentication.getName()).orElseThrow();
верно, вот такой же подход и в остальных случаях

2024-04-15 16:43 UTC, merged